### ISSUE TITLE
Icon badge notification is not appearing on the mobile app's icon

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#1]
When a new general notification comes into the mobile app the alert appears but the badge notification does not a appear with an alert count.

**Comment by jcarterOCV** [comment]
Should be resolved when build 17 comes.  Will test once TestFlight is live.

**Comment by ivr-randallw** [comment]
Confirmed this morning that the badge icon is still not appearing in build 17.

**Comment by rcmp-randallw** [comment]
Badge notification is confirmed working in build 18.
