### ISSUE TITLE
Scrolling alert does not appear on main menu when the app resumes

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#5]
If there is an active alert (current within 24 hours) and you resume the app the scrolling alert does not appear at the bottom of the screen:
![image](https://user-images.githubusercontent.com/47233113/54872825-cc98cb00-4d87-11e9-9acb-16281e0bfa89.png)

until you press and cancel a pop menu item or you go to “Alert History” and return to the main menu:
![image](https://user-images.githubusercontent.com/47233113/54872838-f18d3e00-4d87-11e9-8a0b-a087bd93c86e.png)

**Note: The scrolling alert should appear automatically on an app resume if the alert is current, and not after a user action.**

**Comment by jcarterOCV** [comment]
This will be updated in build 16

**Comment by ivr-randallw** [comment]
Confirmed this morning that with build 17 on initial start up/resume active alerts do not appear until you exit and return to the main menu.

**Comment by rcmp-randallw** [comment]
Please note if you resume the app the scrolling alert will automatically start.

**Comment by jcarterOCV** [comment]
Will be resolved in build 18

**Comment by rcmp-randallw** [comment]
With the phone locked and the display off, on receipt of a new notification with build 18 the notification appears on the lock screen and when pressed the user is prompted to log into the phone and the mobile app is displayed but resumes where the last session ended (you do not go to the alert like before (where the alert banner was black)) and in addition when the app resumes in this fashion the alert is not scrolling.

**Comment by rcmp-randallw** [comment]
In addition, if the app starts or resumes without internet connectivity when the connection resumes and the user is prompted to reload the menu even if there is a current alert the alert will not scroll.

**Comment by rcmp-randallw** [comment]
With build 18 scrolling works on initial startup or if you resume the app after initial startup or you invoke it by moving off the main menu and returning.  Once it is scrolling if you leave the app with it running in the background and you go back to the app shortly thereafter (e.g. immediately to within ~ 5 minutes) the alert will still be scrolling but after an indeterminate period of time but before the landing page is displayed on a resume the app will resume without the alert scrolling.

**Comment by jcarterOCV** [comment]
> when pressed the user is prompted to log into the phone and the mobile app is displayed but resumes where the last session ended (you do not go to the alert like before (where the alert banner was black))
This should be resolved in your current version as it was a server side tweak.

I will look into the ticker more.

**Comment by rcmp-randallw** [comment]
Scrolling alert works on initial startup, resuming after 4 minutes and after 10 minutes.

Scrolling does not work if the app is started without internet connectivity and then the connection is re-established and the user accepts the prompt to reload the menu.

**Comment by jcarterOCV** [comment]
Should be resolved in build 20

**Comment by rcmp-randallw** [comment]
@jcarterOCV The following is still an issue with build 20:

Scrolling does not work if the app is started without internet connectivity and then the connection is re-established and the user accepts the prompt to reload the menu, even when selecting menu items and returning to main.

**Comment by rcmp-randallw** [comment]
@jcarterOCV Also if you close off the app and start the app from fresh the scrolling alert does not work until you press Home and resume the app or select a menu item and return to the main menu.

**Comment by jcarterOCV** [comment]
Should be resolved in build 21

**Comment by rcmp-randallw** [comment]
@jcarterOCV With build 21 if  you close off the app and start the app from fresh the scrolling alert works, however, scrolling does not work if the app is started without internet connectivity and then the connection is re-established and the user accepts the prompt to reload the menu, even when selecting menu items and returning to main or pressing home and resuming the app you will not see the scrolling alert.

**Comment by rcmp-randallw** [comment]
@jcarterOCV There seems to be an edge case on startup (usually involving a longer than usual startup process where the initial page stays up longer than usual) where the alert does not scroll.  It is very intermittent and I have seen it after closing the app and then restarting after a short period of time (10+ seconds).  I will take this as an edge case but just be aware of it to see if some delay in the startup process can trigger this behaviour. Not must fix but would be nice to fix.

**Comment by rcmp-randallw** [comment]
@jcarterOCV This may be related where sometimes when the app starts it get stuck on the initial screen (horse and rider) and never proceeds to the main menu.  May be an intermittent connection issue to the back end at startup?
